name: ui_library
description: Uplink UI Library.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/text/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/text/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/text/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/text/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/text/Poppins-Italic.ttf
          weight: 400

    - family: SpaceMono
      fonts:
        - asset: fonts/text/SpaceMono-Bold.ttf
          weight: 700
          
    - family: UIcons
      fonts:
        - asset: fonts/icon/UIcons.ttf
