# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Running Appium Tests

on:
  workflow_run:
    workflows: ['Flutter CI - Generate APK', 'Comment on pull request with APK file']
    types: [completed]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [25] #Google api level
        target: [default]
        node-version: [14.x]
    steps:
    - name: Checkout ✔️
      uses: actions/checkout@v3 #checkout the code 

    - name: Use Node.js ${{ matrix.node-version }} 🔨
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM dependencies 📦
      run: |
        cd appium-flutter-poc && npm ci

    - name: Install and Run Appium Server 📱
      run: |
        chmod +x ./appium-flutter-poc/scripts/run_appium_server.sh # install and run appium server in the background
        ./appium-flutter-poc/scripts/run_appium_server.sh
    - name: Run Appium Tests 🌡️
      uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: cd appium-flutter-poc && npm run android.ci # running our test with info to check the results
