name: Running Appium Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  
jobs:
  build:
    uses: ./.github/workflows/flutter-CI.yml

  test:
    needs: build
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [25] #Google api level
        target: [default]
        node-version: [14.x]

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: apk-android
        path: ./appium-tests/apps/app-profile.apk

    - name: Checkout ✔️
      uses: actions/checkout@v3 #checkout the code 

    - name: Use Node.js ${{ matrix.node-version }} 🔨
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM dependencies 📦
      run: |
        cd appium-tests && npm ci

    - name: Install and Run Appium Server 📱
      run: |
        chmod +x ./appium-tests/scripts/run_appium_server.sh # install and run appium server in the background
        ./appium-tests/scripts/run_appium_server.sh
    
    - name: Run Appium Tests 🌡️
      uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: cd appium-tests && npm run android.ci # running our test with info to check the results
